#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  gather_facts: False
  roles:
  - name: node
  - name: typescript
  - name: gulp

- tasks:
  - name: install project npm dependencies 
    npm: 
      state:  latest

  - name: call gulp
    command: gulp
