#!/usr/bin/env ansible-playbook
---
- hosts: test
  gather_facts: False
  roles:
  - node
  - typescript
  - gulp

  tasks:
  - name: install project npm dependencies 
    npm: 
      state:  latest

  - name: call gulp
    command: gulp
